name: publish-banner

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'
        required: true
        default: 'main'

jobs:
  publish-banner:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repo
        id: 'checkout-repo'
        uses: actions/checkout@v2

      - name: Install node modules
        id: 'install-node-modules'
        run: 'yarn install'

      - name: Install DCL globally
        id: 'install-dcl'
        run: 'npm install -g decentraland'

      - name: Pack item
        id: 'pack-item'
        run: 'yarn run item banner'

      - name: Authenticate with Google Cloud service
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/820318058476/locations/global/workloadIdentityPools/e9a7e8fcc4b4402ebc037973af174bdd/providers/github'
          service_account: 'backend-339310@appspot.gserviceaccount.com'

      - name: Upload item to Google Cloud Storage
        id: 'upload-item'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: "banner.zip"
          destination: "3stats/dcl-smart-items/banner.zip"
